using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Glimpse for NH (Beta)")]
[assembly: AssemblyDescription("NHibernate plugin for Glimpse. This package adds a tab displaying SQL activity generated by NH 3.2. (Beta)")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("nmolnar, avanderhoorn, stevenlauwers")]
[assembly: AssemblyProduct("Glimpse.Nh")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("dd7528b9-e5b0-41e5-97ed-e5fa4787dfba")]

[assembly: AssemblyVersion("0.87")]
[assembly: AssemblyFileVersion("0.87")]